require: rubocop/cop/github

AllCops:
  DisabledByDefault: true

Bundler/DuplicatedGem:
  Enabled: true

Bundler/OrderedGems:
  Enabled: true

Layout/BlockEndNewline:
  Enabled: true

Layout/EndOfLine:
  Enabled: true

Layout/InitialIndentation:
  Enabled: true

Layout/SpaceAfterColon:
  Enabled: true

Layout/SpaceAfterComma:
  Enabled: true

Layout/SpaceAfterMethodName:
  Enabled: true

Layout/SpaceAfterNot:
  Enabled: true

Layout/SpaceAfterSemicolon:
  Enabled: true

Layout/SpaceAroundBlockParameters:
  Enabled: true

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: true

Layout/SpaceInsideArrayPercentLiteral:
  Enabled: true

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true

Layout/SpaceInsideParens:
  Enabled: true

Layout/SpaceInsideRangeLiteral:
  Enabled: true

Layout/Tab:
  Enabled: true

Layout/TrailingBlankLines:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Layout/SpaceBeforeFirstArg:
  Enabled: true

Layout/EmptyLineBetweenDefs:
  Enabled: true
  AllowAdjacentOneLineDefs: true
  NumberOfEmptyLines: 1

Layout/EmptyLines:
  Enabled: true

Layout/EmptyLinesAroundBeginBody:
  Enabled: true

Layout/EmptyLinesAroundBlockBody:
  Enabled: true

Layout/EmptyLinesAroundClassBody:
  Enabled: true

Layout/EmptyLinesAroundMethodBody:
  Enabled: true

Layout/EmptyLinesAroundModuleBody:
  Enabled: true

Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: true

Layout/ExtraSpacing:
  Enabled: true
  AllowForAlignment: false

Layout/DotPosition:
  Enabled: true
  EnforcedStyle: trailing

Layout/BlockAlignment:
  Enabled: true

Lint/CircularArgumentReference:
  Enabled: true

Layout/ConditionPosition:
  Enabled: true

Lint/Debugger:
  Enabled: true

Layout/DefEndAlignment:
  Enabled: true

Layout/EndAlignment:
  Enabled: true

Lint/DeprecatedClassMethods:
  Enabled: true

Lint/DuplicateMethods:
  Enabled: true

Lint/DuplicatedKey:
  Enabled: true

Lint/EachWithObjectArgument:
  Enabled: true

Lint/ElseLayout:
  Enabled: true

Lint/EmptyEnsure:
  Enabled: true

Lint/EmptyInterpolation:
  Enabled: true

Lint/EndInMethod:
  Enabled: true

Lint/EnsureReturn:
  Enabled: true

Lint/FloatOutOfRange:
  Enabled: true

Lint/FormatParameterMismatch:
  Enabled: true

Lint/LiteralAsCondition:
  Enabled: true

Lint/LiteralInInterpolation:
  Enabled: true

Lint/Loop:
  Enabled: true

Lint/NextWithoutAccumulator:
  Enabled: true

Lint/RandOne:
  Enabled: true

Lint/RequireParentheses:
  Enabled: true

Lint/RescueException:
  Enabled: true

Lint/StringConversionInInterpolation:
  Enabled: true

Lint/UnderscorePrefixedVariableName:
  Enabled: true

Lint/UnneededCopDisableDirective:
  Enabled: true

Lint/UnneededSplatExpansion:
  Enabled: true

Lint/UnreachableCode:
  Enabled: true

Lint/UselessComparison:
  Enabled: true

Lint/UselessSetterCall:
  Enabled: true

Lint/Void:
  Enabled: true

Lint/AmbiguousOperator:
  Enabled: true

Lint/AmbiguousRegexpLiteral:
  Enabled: true

Lint/HandleExceptions:
  Enabled: true

Lint/NestedMethodDefinition:
  Enabled: true

Lint/NonLocalExitFromIterator:
  Enabled: true

Lint/ParenthesesAsGroupedExpression:
  Enabled: true

Lint/ShadowingOuterLocalVariable:
  Enabled: true

Lint/UnusedBlockArgument:
  Enabled: true

Lint/UnusedMethodArgument:
  Enabled: true

Lint/UselessAccessModifier:
  Enabled: true

Lint/UselessAssignment:
  Enabled: true

Lint/UselessElseWithoutRescue:
  Enabled: true

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: true
  Max: 4

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: true

Metrics/PerceivedComplexity:
  Enabled: false

Naming/AsciiIdentifiers:
  Enabled: true

Naming/ClassAndModuleCamelCase:
  Enabled: true

Naming/FileName:
  Enabled: true

Naming/MethodName:
  Enabled: true

Performance/CaseWhenSplat:
  Enabled: false

Performance/Count:
  Enabled: true

Performance/Detect:
  Enabled: true

Performance/DoubleStartEndWith:
  Enabled: true

Performance/EndWith:
  Enabled: true

Performance/RangeInclude:
  Enabled: false

Performance/RedundantMatch:
  Enabled: false

Performance/RedundantMerge:
  Enabled: true
  MaxKeyValuePairs: 1

Performance/Size:
  Enabled: true

Performance/StartWith:
  Enabled: true

Performance/FlatMap:
  Enabled: true
  EnabledForFlattenWithoutParams: false

Performance/ReverseEach:
  Enabled: true

Performance/StringReplacement:
  Enabled: true

Security/Eval:
  Enabled: true

Style/ArrayJoin:
  Enabled: true

Style/BeginBlock:
  Enabled: true

Style/BlockComments:
  Enabled: true

Style/CaseEquality:
  Enabled: true

Style/CharacterLiteral:
  Enabled: true

Style/ClassMethods:
  Enabled: true

Style/Copyright:
  Enabled: false

Style/DefWithParentheses:
  Enabled: true

Style/EndBlock:
  Enabled: true

Style/For:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashSyntax:
  Enabled: true
  EnforcedStyle: ruby19

Style/LambdaCall:
  Enabled: true

Style/MethodCallWithoutArgsParentheses:
  Enabled: true

Style/MethodDefParentheses:
  Enabled: true

Style/MultilineIfThen:
  Enabled: true

Style/NilComparison:
  Enabled: true

Style/Not:
  Enabled: true

Style/OneLineConditional:
  Enabled: true

Style/StabbyLambdaParentheses:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Strip:
  Enabled: true

Style/RedundantSortBy:
  Enabled: true

Style/Sample:
  Enabled: true
